"""Add is_open to RawMaterialReception

Revision ID: 30b49dce8990
Revises: 
Create Date: 2026-01-30 02:06:43.600544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b49dce8990'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawmaterialreception_grower')
    op.drop_table('areas')
    op.drop_table('fumigation_lot')
    op.drop_table('clients')
    op.drop_table('rawmaterialreception_client')
    op.drop_table('growers')
    op.drop_table('roles')
    op.drop_table('fulltruckweights')
    op.drop_table('rawmaterialpackagings')
    op.drop_table('varieties')
    op.drop_table('fumigations')
    op.drop_table('role_user')
    op.drop_table('rawmaterialreceptions')
    op.drop_table('area_user')
    op.drop_table('lots')
    op.drop_table('samplesqc')
    op.drop_table('lotsqc')
    op.drop_table('users')
    op.drop_table('client_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user',
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'user_id')
    )
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=9), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_external', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lotsqc',
    sa.Column('lot_id', sa.INTEGER(), nullable=True),
    sa.Column('analyst', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('units', sa.INTEGER(), nullable=False),
    sa.Column('inshell_weight', sa.FLOAT(), nullable=False),
    sa.Column('shelled_weight', sa.FLOAT(), nullable=False),
    sa.Column('yieldpercentage', sa.FLOAT(), nullable=False),
    sa.Column('lessthan30', sa.INTEGER(), nullable=False),
    sa.Column('between3032', sa.INTEGER(), nullable=False),
    sa.Column('between3234', sa.INTEGER(), nullable=False),
    sa.Column('between3436', sa.INTEGER(), nullable=False),
    sa.Column('morethan36', sa.INTEGER(), nullable=False),
    sa.Column('broken_walnut', sa.INTEGER(), nullable=False),
    sa.Column('split_walnut', sa.INTEGER(), nullable=False),
    sa.Column('light_stain', sa.INTEGER(), nullable=False),
    sa.Column('serious_stain', sa.INTEGER(), nullable=False),
    sa.Column('adhered_hull', sa.INTEGER(), nullable=False),
    sa.Column('shrivel', sa.INTEGER(), nullable=False),
    sa.Column('empty', sa.INTEGER(), nullable=False),
    sa.Column('insect_damage', sa.INTEGER(), nullable=False),
    sa.Column('inactive_fungus', sa.INTEGER(), nullable=False),
    sa.Column('active_fungus', sa.INTEGER(), nullable=False),
    sa.Column('extra_light', sa.FLOAT(), nullable=False),
    sa.Column('light', sa.FLOAT(), nullable=False),
    sa.Column('light_amber', sa.FLOAT(), nullable=False),
    sa.Column('amber', sa.FLOAT(), nullable=False),
    sa.Column('yellow', sa.FLOAT(), nullable=False),
    sa.Column('inshell_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('shelled_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samplesqc',
    sa.Column('grower', sa.VARCHAR(length=64), nullable=True),
    sa.Column('brought_by', sa.VARCHAR(length=64), nullable=True),
    sa.Column('analyst', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('units', sa.INTEGER(), nullable=False),
    sa.Column('inshell_weight', sa.FLOAT(), nullable=False),
    sa.Column('shelled_weight', sa.FLOAT(), nullable=False),
    sa.Column('yieldpercentage', sa.FLOAT(), nullable=False),
    sa.Column('lessthan30', sa.INTEGER(), nullable=False),
    sa.Column('between3032', sa.INTEGER(), nullable=False),
    sa.Column('between3234', sa.INTEGER(), nullable=False),
    sa.Column('between3436', sa.INTEGER(), nullable=False),
    sa.Column('morethan36', sa.INTEGER(), nullable=False),
    sa.Column('broken_walnut', sa.INTEGER(), nullable=False),
    sa.Column('split_walnut', sa.INTEGER(), nullable=False),
    sa.Column('light_stain', sa.INTEGER(), nullable=False),
    sa.Column('serious_stain', sa.INTEGER(), nullable=False),
    sa.Column('adhered_hull', sa.INTEGER(), nullable=False),
    sa.Column('shrivel', sa.INTEGER(), nullable=False),
    sa.Column('empty', sa.INTEGER(), nullable=False),
    sa.Column('insect_damage', sa.INTEGER(), nullable=False),
    sa.Column('inactive_fungus', sa.INTEGER(), nullable=False),
    sa.Column('active_fungus', sa.INTEGER(), nullable=False),
    sa.Column('extra_light', sa.FLOAT(), nullable=False),
    sa.Column('light', sa.FLOAT(), nullable=False),
    sa.Column('light_amber', sa.FLOAT(), nullable=False),
    sa.Column('amber', sa.FLOAT(), nullable=False),
    sa.Column('yellow', sa.FLOAT(), nullable=False),
    sa.Column('inshell_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('shelled_image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('lot_number', sa.INTEGER(), nullable=False),
    sa.Column('packagings_quantity', sa.INTEGER(), nullable=False),
    sa.Column('net_weight', sa.FLOAT(), nullable=True),
    sa.Column('has_qc', sa.BOOLEAN(), nullable=False),
    sa.Column('fumigation_status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('on_warehouse', sa.BOOLEAN(), nullable=False),
    sa.Column('rawmaterialreception_id', sa.INTEGER(), nullable=False),
    sa.Column('variety_id', sa.INTEGER(), nullable=False),
    sa.Column('rawmaterialpackaging_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rawmaterialpackaging_id'], ['rawmaterialpackagings.id'], ),
    sa.ForeignKeyConstraint(['rawmaterialreception_id'], ['rawmaterialreceptions.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number')
    )
    op.create_table('area_user',
    sa.Column('area_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('area_id', 'user_id')
    )
    op.create_table('rawmaterialreceptions',
    sa.Column('waybill', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('truck_plate', sa.VARCHAR(length=6), nullable=False),
    sa.Column('trucker_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('observations', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('fumigations',
    sa.Column('work_order', sa.VARCHAR(length=64), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('real_end_date', sa.DATE(), nullable=True),
    sa.Column('real_end_time', sa.TIME(), nullable=True),
    sa.Column('work_order_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order')
    )
    op.create_table('varieties',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rawmaterialpackagings',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tare', sa.FLOAT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fulltruckweights',
    sa.Column('loaded_truck_weight', sa.FLOAT(), nullable=False),
    sa.Column('empty_truck_weight', sa.FLOAT(), nullable=False),
    sa.Column('lot_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growers',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('csg_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('rawmaterialreception_client',
    sa.Column('reception_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reception_id'], ['rawmaterialreceptions.id'], ),
    sa.PrimaryKeyConstraint('reception_id', 'client_id')
    )
    op.create_table('clients',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.VARCHAR(length=128), nullable=False),
    sa.Column('comuna', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('fumigation_lot',
    sa.Column('fumigation_id', sa.INTEGER(), nullable=False),
    sa.Column('lot_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fumigation_id'], ['fumigations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('fumigation_id', 'lot_id')
    )
    op.create_table('areas',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rawmaterialreception_grower',
    sa.Column('reception_id', sa.INTEGER(), nullable=False),
    sa.Column('grower_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['grower_id'], ['growers.id'], ),
    sa.ForeignKeyConstraint(['reception_id'], ['rawmaterialreceptions.id'], ),
    sa.PrimaryKeyConstraint('reception_id', 'grower_id')
    )
    # ### end Alembic commands ###
